In [1]:
import pandas as pd
import numpy as np
from scipy.stats import wilcoxon

from sfc import *

In [2]:
#datasets = ['../../data/thrombosis_non_thrombosis_v3.csv',
#           '../../data/type_I_vs_type_II_v3.csv',
#           '../../data/type_I_PE_vs_Type_II_v3.csv',
#           '../../data/type_I_vs_Type_II_no_PE_v3.csv']

#biodata = pd.read_csv('../../data/thrombosis_non_thrombosis_v3.csv', sep="\t")
#biodata.drop(['node'], axis='columns', inplace=True)
#biodata = pd.read_csv('/tmp/FVIII_inhibit_dataset_v2.csv', sep="\t")
#biodata.drop(['leg_pos', 'Residue', 'Domain'], axis='columns', inplace=True)
#biodata = pd.read_csv('../../data/type_I_vs_type_II_v2.csv', sep="\t")
#biodata = pd.read_csv('../../data/type_I_PE_vs_Type_II_v2.csv', sep="\t")
#biodata = pd.read_csv('../../data/type_I_vs_Type_II_no_PE_v2.csv', sep="\t")
biodata = pd.read_csv('/tmp/hemophilia-A-FVIII.csv', sep=",")
#biodata.drop(['leg_pos', 'Residue', 'Domain'], axis='columns', inplace=True)

biodata = pd.read_csv('/home/brenno/Documentos/Doutorado/single-feature-classification/data/A-FVIII/hemophilia-A-FVIII.csv', sep=",")

for i in np.arange(biodata.shape[1]-1):
    biodata.iloc[:, i] = (biodata.iloc[:, i] - min(biodata.iloc[:, i]))/(max(biodata.iloc[:, i]) - min(biodata.iloc[:, i]))

biodata

AA_dist       psi       phi   bfactor   areaSAS   areaSES  \
0    0.763500  0.922638  0.197532  0.000350  0.023615  0.162151   
1    0.607157  0.552252  0.973604  0.678162  0.000000  0.000000   
2    0.678268  0.826683  0.400359  0.942926  0.057169  0.336480   
3    0.793477  0.997729  0.206558  0.752523  0.244040  0.614719   
4    0.731317  0.316637  0.220884  0.949290  0.148290  0.360628   
..        ...       ...       ...       ...       ...       ...   
644  0.548863  0.938837  0.091641  0.669097  0.048693  0.116454   
645  0.634333  0.883521  0.089499  0.907674  0.213936  0.297620   
646  0.620312  0.887635  0.083343  0.823231  0.000000  0.000000   
647  0.484386  0.323870  0.110254  0.860453  0.282940  0.511179   
648  0.469079  0.345607  0.680162  0.787060  0.728386  0.817634   

     kdHydrophibicity  consurfDB  degree  betweenness  closeness     burts  \
0            0.922222   0.102856     0.6     0.091231   0.696725  0.125538   
1            0.700000   0.048161     0.8     0.041372   0.587920  0.057252   
2            0.966667   0.114230     0.5     0.017761   0.515921  0.146744   
3            0.922222   0.262343     0.5     0.019185   0.464209  0.183612   
4            0.111111   0.070910     0.2     0.011172   0.472866  0.349874   
..                ...        ...     ...          ...        ...       ...   
644          0.422222   0.147628     0.8     0.080131   0.447783  0.081437   
645          0.355556   0.235963     0.7     0.240464   0.412651  0.070102   
646          1.000000   0.124637     0.5     0.006550   0.249254  0.170809   
647          0.111111   0.455954     0.5     0.050101   0.206609  0.134053   
648          0.144444   0.445547     0.2     0.000139   0.066467  0.413263   

           pr      auth  kcore   group  
0    0.532679  0.114591    1.0  Severe  
1    0.745260  0.126035    1.0  Others  
2    0.511582  0.067187    1.0  Severe  
3    0.552450  0.053706    1.0  Others  
4    0.240116  0.007450    1.0  Others  
..        ...       ...    ...     ...  
644  0.815549  0.001685    1.0  Others  
645  0.718814  0.000912    1.0  Others  
646  0.454348  0.000178    1.0  Others  
647  0.536923  0.000067    1.0  Severe  
648  0.216035  0.000013    1.0  Others  

[649 rows x 16 columns]

In [5]:
# dataset 01
acc, f1, nn, auc = runSFC(biodata, nrepetitions = 50, positive='Others', classThreshold = 0.5)
# dataset 02
#acc, f1 = runSFC(biodata, nrepetitions = 50, positive='Type_II', classThreshold = 0.8)

Running SFC on label index = 15

Class: Others -- Size: 497

Class: Severe -- Size: 152

Positive class: Others | Negative Class:Severe
Analyzing iteration 0
Same indexes 0
train: [479  74 493 353 215 249 164 622 492 592 438 332 354  66 115 242 465 405
 292 636 580 311 481 590 500 170 461  77 256 525  51  94 132 172  93 551
  10 255 563 246 635 320 314 227 488 198 634 277 442 252 643 297 199 391
 340 118 271  65 166 361 278 366 196  78 207  39 287 559 250 403   7 615
 480 407 150 567 605  62 541 362 413 209 286 171 276 626  68 149 358 469
 175  32 625 533 597 168  80 319 288 282 462 478 383 212 204 243 639 544
 372 315 283 602 535 379 295 363  61 632 437  63 381 105 342 312 396 596
 499 550 142 591  28 456 167 510 640 157 364 497  55 254 571 318 508 410
 423 300 523 257 156  35 569 588 432  97 369 430  21 578 177 389 607 217
  43 190 219 103 152   0 539 188  87  46 344 135 138  57 387 104 392 181
 370 457 402  20  42 470 514 345 148 515 191  22  70 425 262 601  19 265
  37 137   2 397 

In [8]:
np.round(np.mean(nn[:,0]),2)

5.0

In [33]:
train_idx = np.arange(1,5)
train_idx

array([1, 2, 3, 4])

In [34]:
test_idx = np.arange(4,10)
test_idx

array([4, 5, 6, 7, 8, 9])

In [35]:
not set(train_idx).isdisjoint(set(test_idx))

True

In [9]:
nn[:,0]/10

array([0.3, 0.3, 0.9, 0.4, 0.7, 0.4, 0.6, 0.3, 0.6, 0.5])

In [25]:
print(f'Accuracies - class 01: {np.round(np.mean(acc[:,0]), 2)} | class 02: {np.round(np.mean(acc[:,1]), 2)} | F1: {np.round(np.mean(f1),2)}')

Accuracies - class 01: 0.75 | class 02: 1.0 | F1: 0.81


In [6]:
len(np.where(np.arange(1,10) > 7)[0])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

2

In [5]:
#!/usr/bin/env python
# coding: utf-8

import pandas as pd
import numpy as np
from scipy.stats import wilcoxon

datasets = ['../../data/thrombosis_non_thrombosis_v3.csv',
           '../../data/type_I_vs_type_II_v3.csv',
           '../../data/type_I_PE_vs_Type_II_v3.csv',
           '../../data/type_I_vs_Type_II_no_PE_v3.csv']

acc_01 = []
acc_02 = []
f1_all = []
acc_01_sd = []
acc_02_sd = []
f1_all_sd = []
n_inst_mean = []

dataset_names = []
threshold_values = []

ds = '../../data/thrombosis_non_thrombosis_v3.csv'
t = 0.5

In [6]:
print(f'Analyzing the dataset:{ds} using threshold {t}')
pos_lab = 'Type_II'

if "thrombosis" in ds:
    pos_lab = 'Thrombosis'

biodata = pd.read_csv(ds, sep="\t")
biodata.drop(['node'], axis='columns', inplace=True)

#normalizing...
for i in np.arange(biodata.shape[1]-1):
    biodata.iloc[:, i] = (biodata.iloc[:, i] - min(biodata.iloc[:, i]))/(max(biodata.iloc[:, i]) - min(biodata.iloc[:, i]))



Analyzing the dataset:../../data/thrombosis_non_thrombosis_v3.csv using threshold 0.5


In [7]:
dataset = biodata
nrepetitions = 100
class_idx = np.nan
testSize_smaller_class = 10
classThreshold = 0.5
positive = 'Thrombosis'
seed=100

In [8]:
np.random.seed(seed)
if(np.isnan(class_idx)):
    class_idx =  dataset.shape[1]-1

print(f"Running SFC on label index = {class_idx}\n")

index_by_class = []
smaller_size = dataset.shape[0]    

for class_value in np.unique(dataset.iloc[:,class_idx]):
    temp_idx = np.where(dataset.iloc[:,class_idx] == class_value)[0]
    print(f"Class: {class_value} -- Size: {len(temp_idx)}\n")
    index_by_class.append(temp_idx)
    if len(temp_idx) < smaller_size:
        smaller_size = len(temp_idx)

accuracy_vec = np.zeros((nrepetitions, len(index_by_class)))
n_inst_threshold = np.zeros((nrepetitions, len(index_by_class)))

negative = np.unique(dataset.iloc[:,class_idx]).tolist()
negative.remove(positive)
negative = negative[0]

print(f"Positive class: {positive} | Negative Class:{negative}")
f1 = []
#temp1 = np.nan
#temp2 = np.nan
#temp3 = np.nan

Running SFC on label index = 5

Class: Non_thrombosis -- Size: 283

Class: Thrombosis -- Size: 136

Positive class: Thrombosis | Negative Class:Non_thrombosis


In [9]:
rep = 1


In [11]:
def runXGBoost(train_fold, test_fold, positive, negative, metric = 'auc', class_idx = np.nan):
    if(np.isnan(class_idx)):
        class_idx =  train_fold.shape[1]-1

    x_train = train_fold.drop(train_fold.columns[class_idx], axis=1)
    y_train = train_fold.iloc[:,class_idx]
    y_train.replace(to_replace=[negative, positive], value=[0,1], inplace=True)

    x_val = test_fold.drop(test_fold.columns[class_idx], axis=1)
    y_val = test_fold.iloc[:,class_idx]
    y_val.replace(to_replace=[negative, positive], value=[0,1], inplace=True)

    d_train = xgb.DMatrix(x_train, y_train)
    d_test = xgb.DMatrix(x_val, y_val)

    params = {'booster': 'gbtree',
        'objective': "binary:logistic",
        'nthread': 4,
        'eval_metric': metric}

    myfit = xgb.train(params = params,
        dtrain = d_train,
        num_boost_round = 100,
        maximize = True)

    return (myfit.predict(d_test))

In [13]:
def get_statistical_weights(inputSet, ignore_class = np.nan):
    
    myWeights = np.repeat(np.nan, inputSet.shape[1]-1)

    if(np.isnan(ignore_class)):
        ignore_class =  inputSet.shape[1]-1

    numpy2ri.activate()
    coln = np.delete(np.arange(inputSet.shape[1]), ignore_class)    
    for i in np.arange(len(coln)):
        myWeights[i] = call_wilcox_R(inputSet.iloc[:,coln[i]],
                            inputSet.iloc[:,ignore_class])

        
    numpy2ri.deactivate()

    return (1/myWeights)

In [16]:
import numpy as np
import rpy2.robjects as robjects
from rpy2.robjects import r
from rpy2.robjects import numpy2ri
import xgboost as xgb
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

def call_wilcox_R (x, y):
    r.assign("x", x.to_numpy())
    r.assign("y", y.to_numpy())
    r('res<-wilcox.test(x~y)$statistic')
    r_result = r("res")
    return (r_result[0])

In [18]:
def weighted_mean(x, w):
    return np.dot(x, w)/np.sum(w)

In [21]:
print(f"Analyzing iteration {rep}")

test_idx = np.random.choice(index_by_class[0], testSize_smaller_class, replace=False)
train_idx = np.random.choice(np.delete(index_by_class[0],
    np.where(np.isin(index_by_class[0], test_idx))), smaller_size, replace=False)


for next_class in np.arange(start=1, stop=len(index_by_class)):
    temp_test_idx = np.random.choice(index_by_class[next_class], testSize_smaller_class, replace=False)
    test_idx = np.concatenate((test_idx, temp_test_idx))
    train_idx = np.concatenate((train_idx, 
        np.random.choice(np.delete(index_by_class[next_class], 
        np.where(np.isin(index_by_class[0], temp_test_idx))), smaller_size, replace=False)))


train_set = dataset.iloc[train_idx, :]
test_set = dataset.iloc[test_idx, :]

result_by_att = np.zeros((test_set.shape[0], test_set.shape[1]-1))
#fitting a model per attribute
for att in np.delete(np.arange(train_set.shape[1]), class_idx):
    result_by_att[:, att] = runXGBoost(train_set.iloc[:, [att, class_idx]], 
                            test_set.iloc[:, [att, class_idx]], positive, negative)     

statistical_weights = get_statistical_weights(train_set)
prediction = np.apply_along_axis(weighted_mean, 1, result_by_att, w = statistical_weights)

y_pred = np.repeat(0, test_set.shape[0])
y_pred[np.where(prediction > classThreshold)] = 1
y_true = test_set.iloc[:,class_idx].replace(to_replace=[negative, positive], value=[0,1])


Analyzing iteration 1


In [ ]:
acc_class1 = length(which(testSet$type == class1 & testSet$pred < (1 - classThreshold))) / length(which(testSet$type == class1 & (testSet$pred > classThreshold | testSet$pred < (1 - classThreshold)))) * 100


In [23]:
prediction

array([0.42853667, 0.38566353, 0.54498058, 0.39818268, 0.62742653,
       0.3988251 , 0.53769019, 0.41419275, 0.53546336, 0.29730271,
       0.75480496, 0.6722536 , 0.70516366, 0.71073357, 0.65790612,
       0.60064691, 0.76164615, 0.7566317 , 0.55884421, 0.61391193])

In [37]:
class1 = 0
class2 = 1
classThreshold = 0.6

In [38]:
prediction

array([0.42853667, 0.38566353, 0.54498058, 0.39818268, 0.62742653,
       0.3988251 , 0.53769019, 0.41419275, 0.53546336, 0.29730271,
       0.75480496, 0.6722536 , 0.70516366, 0.71073357, 0.65790612,
       0.60064691, 0.76164615, 0.7566317 , 0.55884421, 0.61391193])

4

5